### ISSUE TITLE
GUI: Add device off reason

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#731] opened 2020-11-18 08:55 UTC
Since a while the device off reason has been added to VictronConnect.\
This has proven to be a great success, so the next logical step would be to add it to the GUI as well.

Products that support the device off reason:
- [VE.Direct MPPTs](https://github.com/victronenergy/vedirect_interface/blob/master/firmware/src/vedirect_solar.c#L79); not sure if this is supported by the older models, but the Smart models should support it
- [Phoenix Smart IP43 Chargers](https://github.com/victronenergy/vedirect_interface/blob/2fd38ded083146bf7fc3d1dfe6f2009e10ba9cae/firmware/src/vedirect_charger.c#L32)
- [VE.Direct Phoenix Inverters](https://github.com/victronenergy/vedirect_interface/blob/2fd38ded083146bf7fc3d1dfe6f2009e10ba9cae/firmware/src/vedirect_inverter.c#L66)
- [VE.Direct Inverter RS](https://github.com/victronenergy/vedirect_interface/blob/2fd38ded083146bf7fc3d1dfe6f2009e10ba9cae/firmware/src/vedirect_multic.c#L75)

The VE.Can dbus service does not seem to support the `/DeviceOffReason` path yet.\
However, the device off reason is supported by the following products:
- VE.Can Smart MPPTs
- Inverter RS

The VREG that corresponds to `/DeviceOffReason` is [`VE_REG_DEVICE_OFF_REASON_2`](https://github.com/victronenergy/velib/blob/master/inc/velib/ve_regs.h#L789); its definition can be found in [vregs.xml](https://github.com/victronenergy/velib/blob/master/data/protocols/vregs.xml).

In VictronConnect the device off reason is available as a `Why is the charger off?` button on the device page.\
See [this ](https://www.victronenergy.com/blog/2020/06/19/victronconnect-v5-26-why-is-the-charger-off/#:~:text=Now%2C%20VictronConnect%20indicates%20precisely%20why%20the%20solar%20charger%20is%20not%20charging.&text=Another%20common%20reason%20for%20Solar,by%20a%20BMS%20%E2%80%93%20battery%20full.)blog post for more details.

Some examples:
<img src="https://user-images.githubusercontent.com/6614648/99506615-9bb8d100-2982-11eb-94e1-27e8418d17f0.png" width=400 /><img src="https://user-images.githubusercontent.com/6614648/99506658-a70bfc80-2982-11eb-925a-6761bcd65309.png" width=400 />

**Comment by izak** [comment] 2021-01-05 13:45
Duplicate of https://github.com/victronenergy/venus-private/issues/101. @jepefe indicated he'd look into it.

**Closed by izak** 2021-01-05 13:45 UTC
