### ISSUE TITLE
Update bluez to v5.72 - fixes connection for Pixel 6

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1206] opened 2024-01-31 06:49 UTC
Thiemo tested this (built the newer Bluez, installed that on a GX, etc.

**Comment by mpvader** [comment] 2024-01-31 06:49
@ThiemoVanEngelen / @jhofstee fyi. Note that I've moved this to v3.30, and removed it from the todo wiki page.

**Comment by jhofstee** [comment] 2024-09-17 13:41
Closing this, since @ThiemoVanEngelen can't reproduce the issue. It can be reopened if needed.

**Closed by jhofstee** 2024-09-17 13:41 UTC
Labels: bug, medium_prio
