### ISSUE TITLE
dbus-valence: bms service has wrong product id

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#46] opened 2016-08-09 08:06 UTC
The product id is set to 0x142, which is the Lynx Ion. It should be 0xB001.

**Comment by martinbosma** [comment] 2016-08-09 08:07
`dbus -y com.victronenergy.bms.valence0 / GetValue
value = {'Balancing': 0,
 'Connected': 1,
 'DeviceInstance': 0,
 'FirmwareVersion': 0,
 'HardwareVersion': '',
 'Io/AllowToCharge': 1,
 'Io/AllowToDischarge': 1,
 'Mgmt/Connection': 'VE.Can',
 'Mgmt/ProcessName': 'dbus_valence',
 'Mgmt/ProcessVersion': '1.4',
 'N2KUniqueNumber': 10,
 'ProductId': 322,
 'ProductName': 'Super B BMS',
 'Serial': '',
 'State': 9,
 'System/BatteriesParallel': 0,
 'System/BatteriesSeries': 4,
 'System/MaxCellVoltage': 0.0,
 'System/MinCellVoltage': 0.0,
 'System/NrOfBatteries': 0,
 'System/NrOfCellsPerBattery': 4}
`

**Comment by mpvader** [comment] 2016-08-09 09:11
assigned to oceanvolt

**Comment by RealAth** [comment] 2016-08-17 11:38
dbus-valence found in latest release candidate stream couldn't found D-Bus services. I updated the velib and it works again. However I couldn't reproduce this product id bug. Command  "dbus -y com.victronenergy.bms.valence0 / GetValue" outputs 'ProductId': 45057,".

New dbus-valence is now available in git (tag is 1.10). executable-name branch is also merged into it (binary name is now dbus-valence instead of dbus_valence).

**Comment by mpvader** [comment] 2016-08-17 12:09
ok. I'll add it to the venus todo list. What is the change log for dbus-valence 1.10?

**Comment by RealAth** [comment] 2016-08-17 12:14
dbus_valence 1.10
- rename the executable dbus-valence
- update velib

**Comment by mpvader** [comment] 2016-08-17 12:31
thanks! I'll close this issue now. You'll see a test version (v1.80~xx) appearing in the coming weeks. We'll email the change log to the [venus-dev mailing group](https://groups.google.com/forum/#!forum/victron-dev-venus).

**Closed by mpvader** 2016-08-17 12:31 UTC
