### ISSUE TITLE
gui: don't pretend that there is a VE.Bus BMS

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#215] opened 2017-10-26 18:34 UTC
On a system with no VE.Bus BMS, and also no VE.Bus BMS installed, the gui shows this:
![image](https://user-images.githubusercontent.com/5200296/32070535-fece4c92-ba8c-11e7-8a28-16f8b38a6486.png)

instead, I'd prefer an empty menu, with just a single line 'No VE.Bus BMS installed'.

The dbus info:
```
Bms/AllowToCharge                       1
Bms/AllowToChargeRate                   0
Bms/AllowToDischarge                    1
Bms/BmsExpected                         0
Bms/Error                               0
```

I noticed this on the BMZ, and also other, test systems in Groningen.

**Comment by mpvader** [comment] 2017-10-26 18:35
@vejpasop can we simply put in that line when `Bms/BmsExpected == 0` ?

Or when `Bms/BmsExpected ==0 && Bms/Error == 0` ?

By the way, what are the definitions of Bms/Error ?

**Comment by jhofstee** [comment] 2017-10-26 19:03
@mpvader 
" can we simply put in that line when /Bms/BmsExpected == 0 "
yes, there is no valid BmsError flag if there is no BmsExpected. Both are found in the same assistant unless things changed. Up to @vejpasop  to confirm.

"Or when /Bms/BmsExpected ==0 && /Bms/Error == 0"
That would be inconsistent with the rest of the UI.

"By the way, what are the definitions of /Bms/Error"
It is a boolean.

I assigned it to myself, since it will be two lines of code.

**Comment by vejpasop** [comment] 2017-10-27 05:41
" can we simply put in that line when /Bms/BmsExpected == 0"
Yes.. Confirmed.

**Comment by vejpasop** [comment] 2017-11-17 10:06
For this to work with the new ESS assistant "two signal" BMS option, mk2-dbus v2.59 is required.
With previous versions  of mk2-dbus /Bms/BmsExpected will remain 0 when the "two signal" BMS is configured.

**Closed** 2017-12-05 16:03 UTC
