### ISSUE TITLE
DVCC regulation

### ISSUE THREAD

**Issue by sunnyday333** [victronenergy/venus#904] opened 2022-02-02 13:55 UTC
Dear team,

I found out that when DVCC is switched on, the regulation does not work exactly as intended. As soon as the battery is charged (CCL is 0A), Venus OS reduces the production from the regulators and does not take into account the actual consumption of all components (regulators, multiplus etc.. and the battery is constantly discharged. This condition continues up to SOC 96% when the battery reaches CCL at some charging level. This situation does not occur if I turn off the DVCC, then the regulation is exactly as intended.

<img width="522" alt="Screenshot 2022-02-02 at 13 32 18" src="https://user-images.githubusercontent.com/89206675/152167303-9dd5af7f-54d3-45c1-a0db-3f278eb1f992.png">

Thank you

**Comment by mpvader** [comment] 2022-02-02 14:16
Hi @sunnyday333 this is by design. All compatible managed batteries don't work with CCL, instead they lower their charged voltage in case they have (for example) a cell on which they want to reduce the voltage.

**Comment by sunnyday333** [comment] 2022-02-02 15:02
Hi @mpvader 
Yes I understand, but CVL (Charge Voltage Limit) is constant. It does not change, so it is strange to me why this discharge occurs.

**Comment by sunnyday333** [comment] 2022-02-03 10:52
Hi @mpvader .

Today I tried the island mode and the regulation is stable in this mode. It does not even drain the battery as I wrote above

![Screenshot 2022-02-03 at 11 47 15](https://user-images.githubusercontent.com/89206675/152328852-11f5ca1e-de0b-4f06-8e26-5141cb914b69.png)
.

**Comment by mpvader** [comment] 2022-02-03 15:04
Correct. To work with our equipment, the battery must *not* set CCL=0.

If the battery sets CCL to 0, then in ESS mode the system will discharge. And in island mode there is no problem.

The solution is to change the software in the battery. It should use CVL, not CCL.

Alternatively, use one of officially compatible batteries. See this list: https://www.victronenergy.com/live/battery_compatibility:start.

I'm sorry, but we really cannot help you any further here: this CVL / CCL control is a complex topic and we don't give support just like that to anyone on this. I hope you understand.

To get more help, in case you are a sizeable battery manufacturer: please contact your Victron distributor, and ask them to contact our sales manager.

Or try this forum: https://community.victronenergy.com/spaces/31/mods.html.

**Comment by sunnyday333** [comment] 2022-02-03 20:51
Hi @mpvader

My battery is on the list of compatible batteries, so I assume that DVCC has been verified and functional when it is forced on from version 2.80. The battery is BMZ ESS Z.

Thank you.

**Comment by mpvader** [comment] 2022-02-03 22:52
Hi @sunnyday333 , that is strange. We will look at that & discuss with BMZ. Meanwhile, the best solution for your system will be to revert to v2.73 I'm afraid. I'll get back to you tomorrow; we should then also move this to a support case, rather then continue here on a github ticket.

Perhaps you can tell me the name of your system? Then I can find it in VRM, analyse it, and also find your email address and contact you from our support system, via email.

**Comment by sunnyday333** [comment] 2022-02-04 08:31
Hi @mpvader,
Thank you, I'll wait for the ticket to open. In the meantime, I downgrade to version 2.73.
I changed the name in the VRM portal to E2BSMK753DWZ for security reasons.

Well, thank you.

**Comment by mpvader** [comment] 2022-02-04 11:21
Hi, thank you - found it. You can change the name again if you want. And you'll receive an email today. I'll close this issue now.

**Closed by mpvader** 2022-02-04 11:21 UTC
