### ISSUE TITLE
Fronius zero power feed-in takes 200W from grid

### ISSUE THREAD

**Issue by edevries-victron** [victronenergy/venus#108] opened 2016-12-15 09:42 UTC
Fronius zero power feed-in try to take at least 200W from grid whenever the PV inverter is not throttled.
This also happens at night with systems that do not shut down when there is no PV power.

Note that this is not a problem whenever the load on AC-Out exceeds 200W or the battery is charged.

**Comment by PizBuin** [comment] 2017-03-14 20:32
Hello,

This 200W topic causes troubles. My target is to minimize grid power usage / maximize self-consumption.

**System Details**
Fronius Galvo 2.0 inverter connected to AC1
Fronius zero feed in selected
Multiplus 24/5000 with ESS assistant
BMV700
Color Control
Victron LFP Batteries + BMS

**1. During night**
To achieve a power consumption of about 0W during the night I have to set the Grid setpoint in the ESS menu to minus 200W.
Furthermore - if CGGX loose the connection to the Fronius inverter while the batteries discharges the feed-in power also rises to 200W which is not allowed for me.

**2. During the day** – when the battery is charged -  the feed-in power goes to 200W which is also not allowed.

**In general**
I also saw, that in the Fronius Galvo page the Zero feed-in power limit is shows 200W - pv power is 0W. Maybe there is a connection to the shown behaviour?

**So my question is**
Are shown problems a result ob this issue?
Is there a schedule to solve this problem? Many thanks in advance.

**Comment by mpvader** [comment] 2017-03-20 18:15
Hi @PizBuin, Yes, sounds like they are related. We are working to fix this. No schedule, sorry. Matthijs

**Comment by PizBuin** [comment] 2017-03-20 19:12
Hi Matthijs,
thanks for your answer. Good to hear that his problem will be solved! If there is an improved test version available please let me know - I will test it.
In general I´m very happy with the ESS - especially with the Fronius Zero feed-in funktion. 
I think it was a big step in the right direktion !
Best regards
Dietmar

**Comment by edevries-victron** [comment] 2017-06-27 12:03
Fixed with hub4control v1.1.4.

**Comment by PizBuin** [comment] 2017-06-27 17:35
Hello,
i would like to test the new version. Which ESS version I have to use?
Best regards
Dietmar

**Comment by mpvader** [comment] 2017-06-28 15:41
ps commenting to issues is also possible after they have been closed. So I'll close it anyway now.

**Comment by mpvader** [comment] 2017-06-28 16:09
I'm sorry, this was not added in v2.08~3. I'll reopen the issue and then delete all my confusing comments. We'll soon add this in a next test release.

**Comment by mpvader** [comment] 2017-06-30 18:40
Added in Venus v2.08~4

@PizBuin you can test it now. More info on working with test versions is [here](https://www.victronenergy.com/live/ccgx:beta-testing)

I'll close the issue now, but please do comment your test results.

**Comment by PizBuin** [comment] 2017-07-08 19:31
I tested v2.08~9. The 200W issue is solved **BUT**

the power control loop works not as expected. PV power stucks at low values and battery will be discharged although there is a plenty of PV power available.

So the battery will be stressed and I loose available PV power which is not satisfying.
Can anybody at Victron have a look at this and find a solution?

So I went back to 2,07 until this issue is solved.


Kind regards Dietmar




**Here is my problem description.**

**System Details**
Fronius Galvo 2.0 inverter connected to AC1
Multiplus 24/5000 with ESS assistant
BMV700
Color Control with Firmware 2.08-9
Victron LFP Batteries + BMS
About 1,6kW peak solar power
Fronius zero feed in selected
Grid setpoint is 0W

Weather: very sunny, 

I started the dishwasher but the CCGX did not rise the PV-Ppower to max. possible value as expected and took almost all power from battery:
- Battery power approx.. 1,8kW
- PV power stayed at approx.. 0,12kW

See picture 1 and 2
![pic1](https://user-images.githubusercontent.com/26417910/27988499-82c97cda-6423-11e7-9ef0-195fb1bdd2fe.jpg)
![pic2](https://user-images.githubusercontent.com/26417910/27988502-8fb7b68c-6423-11e7-840d-4525b4972b29.jpg)

**To verify I turned “fronius zero feed in” off.** 
- Battery power went down to approx. 0,68kW
- PV power went up approx.. 1,2kW

This is what I had expected
See picture 2 and 3

![pic3](https://user-images.githubusercontent.com/26417910/27988506-a4d4e35a-6423-11e7-844f-6da0834259ba.jpg)

![pic4](https://user-images.githubusercontent.com/26417910/27988510-ae475490-6423-11e7-86c0-7c278dacd406.jpg)


**With firmware2.07** (with 200W bug) my work around was to set the Grit set point to -200W.
With this setting the control loop worked fine.  I think that’s the reason why I did not recognised this behaviour in past.
See picture 5 and 6
![pic5](https://user-images.githubusercontent.com/26417910/27988512-b5fdc980-6423-11e7-9988-1cce7df4ba57.jpg)
![pic6](https://user-images.githubusercontent.com/26417910/27988517-be0daa82-6423-11e7-8b2f-d8014c775729.jpg)

**Comment by PizBuin** [comment] 2017-07-08 19:47
Hello,

I tested v2.08~9. The 200W issue is solved  BUT

the power control loop works not as expected. PV power stucks at low 
values and battery will be discharged although there is a plenty of PV 
power available.

So the battery will be stressed and I loose available PV power which is 
not satisfying. Can anybody at Victron verify this at find a solution?

I wrote the details under closed issue #108. Is this the right place?

Have a nice weekend.

Kind regards

Dietmar


------------------------------------------------------------------------
Am 28.06.2017 um 17:34 schrieb mpvader:

**Comment by mpvader** [comment] 2017-07-10 08:58
Hi @PizBuin, yes this is the right place. Thank for this, we'll (re)start on this today, first of all to reproduce the problem.

Note that somehow your comment showed up twice, I removed the second one.

**Comment by mpvader** [comment] 2017-07-14 08:53
In v2.08~10

@PizBuin the problem was not that PV Power get stuck, it was just real slow in responding to load increases. In v2.08~10 we improved this, and PV Power is now increased much faster.

It would be great if you can confirm how this works now on your system. Thanks!.

**Comment by PizBuin** [comment] 2017-07-16 18:03
Firmware 2.08-11
Fronius zero feed: on

**Situation during loading the battery**
Today ESS system took about 0,68kWh energy from grid despite there was enough PV power available.
Power level is shown in red.
The value is up to 77% of produced power – e.g. PV Power was 330W – Power taken from Grid 256W!
These values will increase with longer charge duration e.g. on days with less sun.
![17-07-16-a1](https://user-images.githubusercontent.com/26417910/28249920-104ab240-6a5f-11e7-9bed-99103da56002.jpg)


**Without battery charging**
The power regulation is fine- no red area. I don´t know the behaviour with big loads in this state e.g. switch on of my dishwaser.
![17-07-16-b](https://user-images.githubusercontent.com/26417910/28249850-338a0ba8-6a5e-11e7-86e8-be36e2b144ec.jpg)

**Summary**
The recognised behaviour (too high PV power reduction during high loads) did not occur again. It seems to be better with this firmware. I will do more testing.

But the regulation behaviour during battery loading have to be improved to bring the grid load to adjusted grid set point (in my case 0W).

Especially with longer charge time the grid energy consumption will rise which is not allowed. 

**On sunny days the goal is to reduce grid energy consumption as low as possible.**
Please provide an improved firmware for testing.

PS
I know the regulation to adjusted grid set point is not easy (PV power / load / charger).
Would it be possible to get a testing firmware with adjustable regulation parameters to find optimal values?

**Comment by PizBuin** [comment] 2017-07-17 16:55
Good evening,

i have added my comments and pictures to closed #108.
Please let me know how you will go on.

Many thanks in advance.

Best regards
Dietmar

------------------------------------------------------------------------
Am 14.07.2017 um 10:53 schrieb mpvader:

**Comment by mpvader** [comment] 2017-07-17 19:39
Hi @PizBuin, thanks, we'll look into this again. The developer responsible for this project is currently on holiday, so this may take a little while. We'll put in another comment here once there is news!

**Comment by mpvader** [comment] 2017-08-02 13:05
Hi @PizBuin I have checked several systems, and indeed the system draws some power from the grid while charging the battery. But, by far, most of the power comes from the PV Inverters.

And the 200W issue has been resolved.

We'll release the improvements as you also have them in ~13 as part of the official v2.08 release. And at a later time see if we can further tweak and improve the algorithm.

**Comment by mpvader** [comment] 2017-09-04 09:20
Released as part of v2.09

**Closed by mpvader** 2017-09-04 09:20 UTC
