### ISSUE TITLE
Custom shape for water level sensor input dialog broken

### ISSUE THREAD

**Issue by mradamcollins** [victronenergy/venus#1320] opened 2024-07-22 14:50 UTC
When attempting to add custom points. The add point button does nothing. Only the close button works, but it fails to generate a custom shape even after entering multiple points

**Comment by jhofstee** [comment] 2024-09-16 17:36
A duplicate of https://github.com/victronenergy/gui-v2/issues/1444 I assume, which is closed, so closing this as well.

**Closed by jhofstee** 2024-09-16 17:36 UTC
